[build.environment]
  HUGO_VERSION_DOWNLOAD = "0.140.2"
  HUGO_ENABLEGITINFO = "true"

[build]
  publish = "public"
  command = """\
    mkdir -p "${HOME}/.local/bin" && \
    curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION_DOWNLOAD}/hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    tar -C "${HOME}/.local/bin" -xf "hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    rm "hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    export PATH="${HOME}/.local/bin:${PATH}" && \
    hugo --gc --minify --buildFuture -b $URL
    """

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = """\
    mkdir -p "${HOME}/.local/bin" && \
    curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION_DOWNLOAD}/hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    tar -C "${HOME}/.local/bin" -xf "hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    rm "hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    export PATH="${HOME}/.local/bin:${PATH}" && \
    hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL
    """

[context.branch-deploy]
  command = """\
    mkdir -p "${HOME}/.local/bin" && \
    curl -sLJO "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION_DOWNLOAD}/hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    tar -C "${HOME}/.local/bin" -xf "hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    rm "hugo_extended_${HUGO_VERSION_DOWNLOAD}_Linux-64bit.tar.gz" && \
    export PATH="${HOME}/.local/bin:${PATH}" && \
    hugo --gc --minify -b $DEPLOY_PRIME_URL
    """

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
